#!/usr/bin/env python3

import subprocess
import os
import sys
import re

class Atcodir:
    def __init__(self, contest):
        self.contest = contest.lower()
        self.url = f'https://atcoder.jp/contests/{self.contest}'

    def get_tasks_html(self):
        result = subprocess.run(f'wget -O /dev/stdout {self.url}/tasks', shell=True, encoding='utf-8', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return None if result.returncode != 0 else result.stdout

    def format_title(self, prefix, src):
        src = src.lower()
        result = f'{prefix.upper()}-'
        for ch in src:
            if ch in 'abcdefghijklmnopqrstuvwxyz.':
                result += ch
            else:
                result += '-'
        return result

    def get_tasks(self, html):
        lines = html.split('\n')
        pattern = f'<td><a href="/contests/{self.contest}/tasks/{self.contest}_([a-z])">(.+)</a>'
        tasks = []
        for line in lines:
            match = re.search(pattern, line)
            if match:
                tasks.append(self.format_title(match.group(1), match.group(2)))
        return tasks

    def create_directories(self):
        html = self.get_tasks_html()
        if html:
            tasks = self.get_tasks(html)
            for task in tasks:
                os.makedirs(f'{self.contest}/{task}')
                subprocess.run(f'touch {self.contest}/{task}/main.cpp', shell=True)
                subprocess.run(f'touch {self.contest}/{task}/main.py', shell=True)

if __name__ == '__main__':
    acd = Atcodir(sys.argv[1])
    acd.create_directories()
